### ISSUE TITLE
Hello, will the source code be available soon?

### ISSUE THREAD

**Issue by ppoffice** [rashad101/SGPT-SPARQL-query-generation#1]
Thank you for sharing this amazing project about KGQA. It seems that the latest update to this repository was 5 months ago, and you stated the code is going through a cleaning phase. May I ask if the source code for SGPT ready now?

**Comment by rashad101** [comment]
Hi ppofice,
Thanks for your interest in our work. We schedule the code release by 20th of December. It might happen earlier than that. Thanks for your understanding.
