### ISSUE TITLE
Error while running training

### ISSUE THREAD

**Issue by debayan** [rashad101/SGPT-SPARQL-query-generation#2]
Thanks for your work!

I was unable to run training and found some error, please see attached screenshot.
<img width="1239" alt="Screenshot 2023-02-02 at 18 34 13" src="https://user-images.githubusercontent.com/185378/216332759-bbfff5ba-e797-4241-b34e-6a412973246a.png">

**Comment by SteinerPascal** [comment]
@debayan did you get it to run eventually? I'm also interested in the project and would like to test it.

**Comment by makevin23** [comment]
I faced the same error when I train it on vquanda and LC-QuAD. I was able to train on qald-9.

**Comment by rashad101** [comment]
Fixed the bug: errors in training script
