### ISSUE TITLE
Data preprocessing 

### ISSUE THREAD

**Issue by troixanhvuctham** [rashad101/SGPT-SPARQL-query-generation#3]
Hello, thank you for your work

I see the json data files you are using are a bit different with the original data. For example in the lcquad2 dataset your data have the "triples_template", but in the original data does not contain.

Can you provide the code or the way you process the data?
Thank you

**Comment by rashad101** [comment]
Hi, 
I contacted the author who processed the data to obtain the triples_template. It was run in a server where he does not have access to anymore unfortunately. Nevertheless, I think triples_template are not used during the training. Sorry for the inconvenience and thank you for your understanding.
